[project]
name = "nitic-introduction-to-deep-learning"
version = "0.1.0"
description = "Jupyter Book (MyST) materials for NITIC deep learning course"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "matplotlib>=3.10.8",
    "matplotlib-fontja>=1.1.0",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "plotly>=6.0.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "tabulate>=0.10.0",
    "torch>=2.11.0",
]

[dependency-groups]
dev = [
    "jupyter-book>=2.1.4",
    "sphinxcontrib-mermaid>=2.0.1",
]
